version: '3.8'

services:
  web:
    build: .
    container_name: bilet-satin-alma-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    working_dir: /var/www/html
    networks:
      - bilet-network

networks:
  bilet-network:
    driver: bridge